import type {NextPage} from 'next'
import Head from 'next/head'
import Parse from "../algorithms/parse";
import App from "../ui/App";

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>pars</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <App/>
        </div>
    )
}

export default Home
